### ISSUE TITLE
Pipeline

### ISSUE THREAD

**Issue by josejachuf** [gi0baro/weppy-REST#5]
Hi @gi0baro 

In reference to the thread [1]
Is it a bug?
For now I solved it with a subclass of RESTModule

Jose

[1] https://groups.google.com/forum/#!topic/weppy-talk/50DcygmWxzU

**Comment by gi0baro** [comment]
@josejachuf nope, is not a bug. It's not intended to be used in the way you're trying to.

Can you clarify the use case for what you need? Because if you need to apply a pipe to the entire rest module the simplest way is to create a normal module with that pipe and then define the rest module as a nested one.

The REST app module contains in the inside 5 different pipelines for the relevant routes, if you want to customize them then you need to create a subclass.

**Comment by josejachuf** [comment]
Thanks @gi0baro . As you say, I have solved it with subclass.
I have a **UserGroupPipe** pipe that I use to validate user roles
`
UserGroupPipe (allowed_groups = ['role1', 'role3'])`

with subclass it works fine, but I thought it could be a bug that did not accept the pipe at module level.
Everything is clear.
Thank you.
José
